### ISSUE TITLE
add robot pose in 2D nav widget 

### ISSUE THREAD

**Issue by kunzel** [strands-project/strands_webtools#12]

**Comment by hawesie** [comment]
The 2D nav widget requires a Pose published to /robot_pose. but the nav stack publishes PoseWithCovarianceStamped to /amcl_pose. Once the required pose appears the robot pose appears in the 2D nav widget. 

As a work around I have created a node to republish the pose: https://github.com/strands-project/strands_utils/blob/master/src/scripts/republish_robot_pose.py 

Run this with `rosrun strands_utils republish_robot_pose.py`

I've also created an issue on the nav2djs repo: https://github.com/WPI-RAIL/nav2djs/issues/26
