### ISSUE TITLE
rosbridge only serves one connection at a time

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_webtools#24]
It appears that rosbridge cannot handle multiple connections. This will be a problem in the future. The video is streamed perfectly well to multiple clients, but the maps aren't.

**Comment by marc-hanheide** [comment]
Problem appears to be that the map_server only published the map once to each client. So, rosbridge gets stuck when waiting for the map for the second client:

```
[INFO] [WallTime: 1376036754.951146] Client connected.  2 clients total.
[INFO] [WallTime: 1376036755.062381] [Client 2] Subscribed to /amcl_pose
[INFO] [WallTime: 1376036755.067596] [Client 2] Subscribed to /tf2_web_republisher/status
[INFO] [WallTime: 1376036755.068204] [Client 2] Subscribed to /tf2_web_republisher/feedback
[INFO] [WallTime: 1376036755.068691] [Client 2] Subscribed to /tf2_web_republisher/result
[INFO] [WallTime: 1376036755.069790] [Client 2] Subscribed to /map
```

This is well known: https://github.com/RobotWebTools/rosbridge_suite/issues/1

**Comment by kunzel** [comment]
Could we this problem maybe be solved if the ROS service of the map_server is used instead of the /map topic?

**Comment by marc-hanheide** [comment]
It is said in the map server repository that the service is somewhat deprecated and might be abolished in future versions. 
The problem is a note general one in rosbridge with all latched topics. It should best be fixed there but no solution is proposed yet. 
We could implement the service interface solution as a hack, but it's not nice.

**Comment by marc-hanheide** [comment]
I cherry-picked a fix from https://github.com/strands-project/rosbridge_suite/commit/c0aaa5c1b108d25a6f45451544906b8a8fcbb7fb that now resolved it.
