### ISSUE TITLE
Swap nav2djs submodule from kunzel/nav2djs to WPI-RAIL/nav2djs

### ISSUE THREAD

**Issue by kunzel** [strands-project/strands_webtools#33]
The navigation with orientation has been included in the official release (r 2) of the nav2djs webtool. Therefore there is no reason to to use my forked version anymore.

**Comment by hawesie** [comment]
Great stuff :)

**Comment by marc-hanheide** [comment]
coolio!

**Comment by marc-hanheide** [comment]
@kunzel have you made this change already?

**Comment by kunzel** [comment]
No, not yet. But I can have a look into it by tomorrow.

**Comment by kunzel** [comment]
Realized by #41
